version: 2

python:
  version: 3
  install:
    - requirements: requirements/development.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: documentation/source/conf.py
  fail_on_warning: false

conda:
  environment: documentation/environment.yaml