# -*- coding: utf-8 -*-
import sys
import os.path
from setuptools import setup, Extension


# add xml_parser_generator to the import path list
base_dir = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, os.path.join(base_dir, "xml_parser_generator"))

from setuptools_builder import CustomBuild, CustomBuildExt


long_desc = """
Breathe is an extension to reStructuredText and Sphinx to be able to read and
 render `Doxygen <http://www.doxygen.org>`__ xml output.
"""

setup(
    long_description=long_desc,
    ext_package="breathe",
    ext_modules=[
        Extension(
            "_parser",
            [],  # source is generated by CustomBuildExt
            depends=CustomBuildExt.M_DEPENDENCIES,
            libraries=["expat"],
            define_macros=[
                ("PARSER_PY_LIMITED_API", "0x03080000"),  # set Stable ABI version to 3.8
                ("MODULE_NAME", "_parser"),
                ("FULL_MODULE_STR", '"breathe._parser"'),
            ],
            py_limited_api=True,
        )
    ],
    cmdclass={"build": CustomBuild, "build_ext": CustomBuildExt},
)
