<<<<<<< HEAD
||||||| 542ae9b
# -*- coding: utf-8 -*-
#
# Test Breathe Warnings documentation build configuration file, created by
# sphinx-quickstart on Thu Jun  5 18:57:21 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.
#
=======
# Test Breathe Warnings documentation build configuration file, created by
# sphinx-quickstart on Thu Jun  5 18:57:21 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.
#
>>>>>>> memberdef-in-groups
# mypy: ignore-errors
from __future__ import annotations

import sys

sys.path.append("../../")

extensions = ["breathe"]

# Breathe configuration parameters
breathe_projects = {
    "class": "../../../examples/doxygen/class/xml/",
    "function": "../../../examples/specific/functionOverload/xml/",
    "group": "../../../examples/specific/group/xml/",
    "invalidproject": "invalid/path/",
}

master_doc = "index"
project = "Test Breathe Warnings"
html_theme = "default"
